### ISSUE TITLE
Appear at the bottom of the page when enabling Centre Alignment

### ISSUE THREAD

**Issue by wznmickey** [kudoai/duckduckgpt#11]
If enable Centre Alignment in ddg, it appears at the bottom of the page.
![图片](https://github.com/kudoai/duckduckgpt/assets/44784663/f7a7fc3e-55f5-4ef5-951f-ab7c4ab85949)

**Comment by adamlui** [comment]
@wznmickey from where do you enable center alignment?

**Comment by wznmickey** [comment]
https://duckduckgo.com/settings#appearance

**Comment by wznmickey** [comment]
https://duckduckgo.com/settings#appearance

**Comment by adamlui** [comment]
@wznmickey thansk for the info, it is fixed to appear on top when in centered mode now:

![image](https://github.com/kudoai/duckduckgpt/assets/10906554/997c199a-4878-492c-930d-a7d04d14da17)

You can update it @ https://greasyfork.org/scripts/459849-duckduckgpt (or it will auto-update eventually)
