### ISSUE TITLE
language of chat-gtp when answering?

### ISSUE THREAD

**Issue by gitttt54** [kudoai/duckduckgpt#12]
Hi,

depending on the searchterm, chatgtp answers in different languages (sometimes even french) ;-D

is there a way to set up a preferred language to have chat-gpt answer the questions/serchterms?

and thank you for that neat idea !

**Comment by adamlui** [comment]
Yes there is a way, when I haev time I will add this then tag you @gitttt54, thank you for the suggestion!

**Comment by adamlui** [comment]
@gitttt54 it is added now, you can set it from this menu:

![image](https://github.com/kudoai/duckduckgpt/assets/10906554/ad8dfc02-6772-4e05-9ff8-a32e2bcd2f24)

You can update by clicking this link: https://greasyfork.org/scripts/459849/code/duckduckgpt.user.js

**Comment by gitttt54** [comment]
thank you very much! that was amazingly quick!

**Comment by adamlui** [comment]
@gitttt54 you're welcome & thank you too, I added you as [contributor](https://github.com/kudoai/duckduckgpt#contributors)! If you want, you could help out by leaving a rating on [Product Hunt](https://www.producthunt.com/products/duckduckgpt/reviews/new) or [Greasy Fork](https://greasyfork.org/en/scripts/459849-duckduckgpt/feedback#post-discussion) (there aren't many so your honest feedback would be quite helpful, if you want)

**Comment by gitttt54** [comment]
FYIO, it works most of the time (75%)

But sometimes, "answer in de" does not "work":
<img width="1300" alt="answer in de" src="https://github.com/kudoai/duckduckgpt/assets/96403800/5b2b496a-454e-4360-aa69-02b3f12d4892">

I reckon that's the best it can be ;-D

**Comment by adamlui** [comment]
@gitttt54 maybe if you choose 'German' or the full name of the language, it will be 100% success rate

**Comment by gitttt54** [comment]
Wow ;-) that simple, thank you!

I just though, I need to use a language code and forgot its just "talking" to ChatGPT and no setting of your userscript...
 
I have changed "de" to "German language" and now its seems to work ;-)

Thanks again for providing great and fast help!

<img width="1290" alt="answer in de" src="https://github.com/kudoai/duckduckgpt/assets/96403800/136e5f63-ec8c-458b-b795-4d3cf82489a7">

**Comment by adamlui** [comment]
You're welcome!

**Comment by adamlui** [comment]
@gitttt54 if you can leave a review on https://www.producthunt.com/products/duckduckgpt/reviews/new it would be really helpful because there is only 1 rating and it's 3-star only because the user complained he had to login to chatgpt to use (because at the time there was no Proxy Mode)
