### ISSUE TITLE
How does the proxy works?

### ISSUE THREAD

**Issue by wznmickey** [KudoAI/duckduckgpt#17]
GPT-4 is not free for public. Who is paying for my usage?

**Comment by adamlui** [comment]
@wznmickey the provider of the current proxy API somehow obtained free access, I believe OpenAI is paying

**Comment by adamlui** [comment]
@wznmickey they probably rely on donated keys, it is open source api i think

**Comment by wznmickey** [comment]
What is the provider?

**Comment by adamlui** [comment]
@wznmickey api.aigcfun.com can you read Chinese? If so you can tell me how they pay

**Comment by adamlui** [comment]
@wznmickey also previously I was using api.pawan.krd until my reverse tunnel stopped working, but when I stopped using he was collecting donations for a goal of $150000

**Comment by wznmickey** [comment]
> @wznmickey api.aigcfun.com can you read Chinese? If so you can tell me how they pay

Perviously it is free. 
Now users can donate and get a private key with higher rate. Free user can use the API with limited rate.

**Comment by adamlui** [comment]
I see, the rate is 10/day i think, but ddgpt just gets a new key when that happens

**Comment by adamlui** [comment]
```js
  if (event.responseText.includes('finish_reason')) { // if AIGCF error encountered
      GM_setValue('aigcfKey', false) // clear GM key for fresh getAIGCFkey()

      // Determine index of AIGCF in endpoint map
      let aigcfMapIndex = -1
      for (let i = 0 ; i < proxyEndpointMap.length ; i++) {
          const endpoint = proxyEndpointMap[i]
          if (endpoint.some(item => item.includes('aigcfun'))) {
              aigcfMapIndex = i ; break
      }}

      // Updated AIGCF endpoint w/ fresh key (using fresh IP)
      (async () => { // IIFE to use await
          proxyEndpointMap[aigcfMapIndex][0] = (
              'https://api.aigcfun.com/api/v1/text?key=' + await getAIGCFkey())
          getShowReply(messages, callback) // re-fetch reply
      })()
```
