### ISSUE TITLE
Support for DuckDuckGo mobile interface

### ISSUE THREAD

**Issue by K4Z3R0** [KudoAI/duckduckgpt#19]

**Comment by adamlui** [comment]
Hey @K4Z3R0 what browser and userscript manager are you using?

**Comment by adamlui** [comment]
And tampermonkey works on mobile??

**Comment by adamlui** [comment]
Ok I will see if I can try to get it to work. It may not be today, because I am working on a mobile re-design of https://chatgpt.js.org and I recall in the past testing it was hard to get API to work on mobile browsers (but sincee then I added proxy ones so maybe it will after all)

**Comment by adamlui** [comment]
@K4Z3R0 I recently added mobile support and it works in kiwi! Can you test if it works in yours?

**Comment by adamlui** [comment]
![Screenshot_20231121-132450](https://github.com/KudoAI/duckduckgpt/assets/10906554/7a24bbbe-3f76-4d2f-88c3-e237701ef5cf)
