### ISSUE TITLE
Failed to parse JSON when using Proxy API, never gets a response without

### ISSUE THREAD

**Issue by daemonspudguy** [kudoai/duckduckgpt#2]
I don't even know what is going on, and the console isn't helping. I'm using Vivaldi and Tampermonkey, if that matters.

**Comment by daemonspudguy** [comment]
The token is undefined when proxy is disabled, how do I get a token?

**Comment by adamlui** [comment]
@daemonspudguy hey proxy mode is currently broken due to OpenAI patching my method (but I am working on fix). For unproxied mode you must sign up @ https://chat.openai.com for an account, stay logged in and go to ddg tab and refresh your search

**Comment by adamlui** [comment]
@daemonspudguy proxy mode has been patched to also work now (you can update @ https://greasyfork.org/en/scripts/459849-duckduckgpt )

**Comment by adamlui** [comment]
@daemonspudguy 
![image](https://user-images.githubusercontent.com/10906554/233546658-5a91366d-011f-4242-b173-44dd6543563e.png)

**Comment by daemonspudguy** [comment]
Thanks! Issue closing now!

**Comment by daemonspudguy** [comment]
It isn't getting my token (yes I'm signed in)

**Comment by adamlui** [comment]
> It isn't getting my token (yes I'm signed in)

Can you switch to proxy mode instead?

**Comment by daemonspudguy** [comment]
Yes, and it does work.

**Comment by daemonspudguy** [comment]
I think it might be because I created my account by signing in with Google.

**Comment by daemonspudguy** [comment]
And of course I can't create a new one with the same email.

**Comment by adamlui** [comment]
@daemonspudguy I updated the code, the OpenAI mode should work too now (signing up w/ Google shouldn't have mattered)
