### ISSUE TITLE
not on main page duckduckgo

### ISSUE THREAD

**Issue by MagombaSiriusBlack** [KudoAI/duckduckgpt#23]
Google Crome 116.0.5845.96 a few days ago was on the main search engine, today disappeared. used through a proxy in Russia

**Comment by adamlui** [comment]
hey @MagombaSiriusBlack can you press `Ctrl+Shift+J` and paste any red errors? Also can you try replacing the `// @require ` line's URL w/ `https://raw.githubusercontent.com/kudoai/chatgpt.js/main/dist/chatgpt-1.7.6.min.js`? (I know jsDelivr is banned where you live, this could be potential cause)
