### ISSUE TITLE
my duckduckgpt is very old if it doesn't know windows 11

### ISSUE THREAD

**Issue by gabri25ele** [KudoAI/duckduckgpt#30]
I asked a question about an update and it answered me

I'm sorry, **but Windows 11 hasn't been released yet**. As of my knowledge, KB5031455 is not an update for Windows 11. It may be an update for an older version of Windows or a reference to an unofficial update. I recommend you check the official Microsoft website or help center for further specific information.

the same question made that bingchat obviously has a different answer.

**Comment by adamlui** [comment]
hey @gabri25ele OpenAI just last month allowed ChatGPT to search the web for answers for Plus users and on Bing Chat. Over time though the backend APIs will do the same (for now the knowledge cutoff is 9/2021, a month before Win11 released)
