### ISSUE TITLE
Way to disable sending chatgpt query simultaneously with search query.

### ISSUE THREAD

**Issue by T1mL3arn** [KudoAI/duckduckgpt#33]
I believe not every search query should be sent to chatgpt. Sometimes you don't need it, sometimes you don't want it. But atm there is no way to control it manually.

Feature request:

- an option like "send gpt query on demand"
- some UI to "send search query to gpt on demand" for gpt-sidebar

So when a user activates it no queries are sent to gpt but it is still possible to ask gpt after page is loaded.

**Comment by adamlui** [comment]
Hey @T1mL3arn there's a prefix/suffix mode if you click the userscript manager's icon to the right of address bar, then scroll to DuckDuckGPT

![image](https://github.com/KudoAI/duckduckgpt/assets/10906554/cdfb042f-fe66-4979-8f49-516b16282f95)

Is that a satisfactory feature for your use case, or do you still want your idea?

**Comment by T1mL3arn** [comment]
I tried it and the sidebar is completely gone - it is not shown for both searches: from browser address bar and from ddg page. It is either buggy or doesn't solve the problem.

**Comment by adamlui** [comment]
@T1mL3arn does the ddgpt disappear even if you type "/my question" as ddg search, and prefix mode is the only mode "ON"?

**Comment by adamlui** [comment]
@T1mL3arn I just tested it, when activating Prefix or Suffix mode, the latest one activated becomes the active mode, then any DDG search that contains the prefix or suffix for either mode shows DDGPT, otherwise it hides DDGPT

**Comment by T1mL3arn** [comment]
Oh, that is how to use it properly. So if I type `/query` with prefix mode enabled then I see gpt answer. It is almost the solution. I still would like to see gpt-sidebar regardless of prefix/suffix setting. That can be controlled with another option like "always show gpt sidebar" which is disabled by default (current behavior). 

I also would like to see more info in readme about what every setting do.

**Comment by adamlui** [comment]
@T1mL3arn OK, I'm in the middle of an online course I'm trying to finish before midnight (I respond here to take a break) to receive an early course certificate, then I have to write a blog post, then I will work on making designing an always-visible mode with option to send search query to GPT, then I will work on an updated readme with more detailed explanations for all the new settings added since the old readme

**Comment by T1mL3arn** [comment]
Wow, thank you!

**Comment by adamlui** [comment]
hey @T1mL3arn I got caught up coding other tasks and then my Amazon grocery delivery just arrived and I am feeling sick so I will make some hot food then sleep then wake up and do it

**Comment by adamlui** [comment]
@T1mL3arn I added a standby mode

![ddgpt-standby-mode](https://github.com/KudoAI/duckduckgpt/assets/10906554/947a7c59-1ae7-4bd5-b7d2-ef95af743707)

It will show if one of these is true:

1. "Auto-Get Answers" is OFF
2. "Prefix Mode" is ON
3. "Suffix Mode" is ON

What do you think?

**Comment by adamlui** [comment]
@T1mL3arn I added it what do you think?

![image](https://github.com/KudoAI/duckduckgpt/assets/10906554/b111b36a-67fa-4cff-a868-7ad7a2ca4424)

**Comment by T1mL3arn** [comment]
That's great, thank you!
