### ISSUE TITLE
Add checksumming for external resources so that script works with security setting "Subresource Integrity" set to "Enforce".

### ISSUE THREAD

**Issue by dreirund** [KudoAI/duckduckgpt#45]
You download external resources:

```
// @require             https://cdn.jsdelivr.net/npm/@kudoai/chatgpt.js@2.6.4/dist/chatgpt-2.6.4.min.js
// @require             https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.js
// @require             https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/contrib/auto-render.min.js
// @require             https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js
```

Can you please add security checksumming, so that this script still works with Tampermonkey's security setting "Subresource Integrity" set to "Enforce"?

Regards!

**Comment by adamlui** [comment]
Hey @dreirund I added it but a separate issue, as of few days ago, the answers are only returning on mobile for me, can you confirm it is the same for you?

**Comment by adamlui** [comment]
Never mind I replaced the API endpoint and response parsing logic so it works on desktop too again

**Comment by dreirund** [comment]
> Hey @dreirund I added it but a separate issue, as of few days ago,
> the answers are only returning on mobile for me, can you confirm it
> is the same for you?

I cannot say anythink about that because I do not use any "mobile".

Regards!

**Comment by dreirund** [comment]
I see I now got a bunch of emails spamming me with

> dded @dreirund to contributors (KudoAI/duckduckgpt#45)

Can you please remove me again as contributor?

I do not want to be (mentioned as) a contributor.

Regards!

**Comment by adamlui** [comment]
I removed you @dreirund
