### ISSUE TITLE
doesnt work anymore

### ISSUE THREAD

**Issue by gmiwoj** [KudoAI/duckduckgpt#48]
normal mode never works, says too many requests every time
proxy mode says its waiting for a reply and never replies

it's been like this for weeks now

**Comment by tiagorangel2011** [comment]
+1

**Comment by stofancy** [comment]
+1 not working

**Comment by stofancy** [comment]
+1, udpate to 2024.03.29 still not working.

**Comment by Algiuxs** [comment]
not working

**Comment by gmiwoj** [comment]
install this instead:
https://addons.mozilla.org/pl/firefox/addon/chatgptbox/

does the same thing (and more) but actually works

**Comment by adamlui** [comment]
@gmiwoj @tiagorangel2011 @User3254548 @stofancy @Algiuxs I finally added 2 proxy APIs so the Proxy Mode works again now

**Comment by Algiuxs** [comment]
> @tiagorangel2011 @User3254548 @stofancy @Algiuxs I finally added 2 proxy APIs so the Proxy Mode works again now

Thanks
